import { v4 as uuidv4 } from 'uuid';
import type { HouseholdMember } from '@/types/household';
import type { LifeEvent } from '@/types/lifeEvent';
import { calculateDateAtAge } from '@/types/household';

/**
 * 家族メンバーから自動生成されるライフイベント
 */
export interface GeneratedLifeEvents {
  retirement?: LifeEvent; // 退職イベント
  pensionStart?: LifeEvent; // 年金開始イベント
}

/**
 * 家族メンバーの情報から退職・年金開始のライフイベントを自動生成
 */
export function generateLifeEventsFromMember(
  member: HouseholdMember
): GeneratedLifeEvents {
  const events: GeneratedLifeEvents = {};
  const now = new Date();

  // 退職イベントの生成
  if (
    member.retirementAge &&
    member.employmentStatus !== 'retired' &&
    member.employmentStatus !== 'student' &&
    member.employmentStatus !== 'unemployed'
  ) {
    const retirementDate = calculateDateAtAge(member.birthDate, member.retirementAge);

    // 未来の日付のみ生成
    if (retirementDate > now) {
      events.retirement = {
        id: `auto-retirement-${member.id}`,
        name: `${member.name}の退職`,
        date: retirementDate,
        type: 'oneTime',
        category: 'retirement',
        cost: 0, // 退職金などはユーザーが手動で設定
        description: `${member.name}が${member.retirementAge}歳で退職予定`,
        isAutoGenerated: true,
        linkedMemberId: member.id,
        createdAt: now,
        updatedAt: now,
      };
    }
  }

  // 年金開始イベントの生成
  if (member.pensionStartAge && member.expectedPensionAmount && member.expectedPensionAmount > 0) {
    const pensionStartDate = calculateDateAtAge(member.birthDate, member.pensionStartAge);

    // 継続イベントなので、過去の開始日でも生成（シミュレーション期間中は継続）
    events.pensionStart = {
      id: `auto-pension-${member.id}`,
      name: `${member.name}の年金`,
      date: pensionStartDate,
      type: 'recurring',
      category: 'income',
      monthlyAmount: -member.expectedPensionAmount, // 収入なので負の値
      description: `${member.name}が${member.pensionStartAge}歳から年金受給開始（月額¥${member.expectedPensionAmount.toLocaleString()}）`,
      isAutoGenerated: true,
      linkedMemberId: member.id,
      createdAt: now,
      updatedAt: now,
    };
  }

  return events;
}

/**
 * 全ての家族メンバーからライフイベントを自動生成
 */
export function generateAllLifeEvents(members: HouseholdMember[]): LifeEvent[] {
  const allEvents: LifeEvent[] = [];

  members.forEach((member) => {
    const { retirement, pensionStart } = generateLifeEventsFromMember(member);

    if (retirement) {
      allEvents.push(retirement);
    }
    if (pensionStart) {
      allEvents.push(pensionStart);
    }
  });

  return allEvents;
}

/**
 * 特定のメンバーに紐づく自動生成イベントのIDを取得
 */
export function getAutoGeneratedEventIds(memberId: string): string[] {
  return [`auto-retirement-${memberId}`, `auto-pension-${memberId}`];
}

/**
 * ライフイベントが自動生成されたものかチェック
 */
export function isAutoGeneratedEvent(event: LifeEvent): boolean {
  return event.isAutoGenerated === true;
}
