export type LifeEventCategory = 'education' | 'housing' | 'vehicle' | 'retirement' | 'income' | 'other';
export type LifeEventType = 'oneTime' | 'recurring';

export interface LifeEvent {
  id: string;
  name: string;
  date: Date; // 発生時期
  type: LifeEventType; // 一時/継続
  category: LifeEventCategory;
  cost?: number; // 一時イベントの費用
  monthlyAmount?: number; // 継続イベントの月額（収入の場合は負の値）
  endDate?: Date; // 継続イベントの終了日
  description?: string; // 説明
  memo?: string;
  isAutoGenerated?: boolean; // 自動生成されたイベントかどうか
  linkedMemberId?: string; // 紐付けられた家族メンバーID
  createdAt: Date;
  updatedAt: Date;
}

// 後方互換性のため
export type { LifeEvent as LifeEventLegacy };
